[build]
# Use pip to install dependencies
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[start]
# Define how to start the server
cmd = "python csms.py" # Or replace with your actual entry file name

[deploy]
# Set up automatic deployment on push to main
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
healthcheckPath = "/health"
healthcheckTimeout = 300

[env]
# DB and JWT values must be set in the Railway UI or .env file
PORT = "5000"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "TRUE"

# If your file isn't named app.py, replace this accordingly
