[build]
builder = "nixpacks"

[build.environment]
PYTHON_VERSION = "3.10"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 app:app"

[environment]
DATABASE_URL = { type = "postgresql" }
JWT_SECRET_KEY = { generator = "secret" }
PORT = "5000"

[variables]
FLASK_ENV = "production"